import React, { useEffect, useMemo, useState } from 'react';
import { UserProfile, Wallet, WalletCurrency, WalletTransaction } from '../types';
import { supabaseService } from '../services/supabaseService';
import {
  ArrowDownLeft,
  ArrowLeft,
  ArrowUpRight,
  Download,
  Landmark,
  PlusCircle,
  RefreshCw,
  SendHorizontal,
  Share2,
} from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { format } from 'date-fns';
import { formatAmount } from '../utils/currency';
import { useCurrency } from '../context/CurrencyContext';

interface WalletsProps {
  profile: UserProfile;
}

type WalletAction = 'add' | 'withdraw' | null;

type TransactionMeta = {
  title: string;
  counterparty?: string;
};

function getTransactionMeta(tx: WalletTransaction): TransactionMeta {
  const isTransferOut = tx.reference?.startsWith('transfer_out:');
  const isTransferIn = tx.reference?.startsWith('transfer_in:');
  const counterparty = isTransferOut || isTransferIn ? tx.reference?.split(':')[1] : undefined;

  if (isTransferOut) {
    return { title: 'Transfer Sent', counterparty };
  }
  if (isTransferIn) {
    return { title: 'Transfer Received', counterparty };
  }
  if (tx.type === 'topup') {
    return { title: 'Add Funds' };
  }
  return { title: 'Withdraw' };
}

function buildReceiptMarkup(profile: UserProfile, tx: WalletTransaction) {
  const meta = getTransactionMeta(tx);
  const receiptNumber = `RCT-${tx.id.slice(0, 8).toUpperCase()}`;
  const amount = formatAmount(tx.amount, tx.currency);
  const createdAt = format(new Date(tx.createdAt), 'PPP p');
  const counterpartyLine = meta.counterparty ? `<p><strong>Counterparty ID:</strong> ${meta.counterparty}</p>` : '';

  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>${receiptNumber}</title>
    <style>
      body { font-family: Arial, sans-serif; background: #f8fafc; color: #0f172a; margin: 0; padding: 24px; }
      .receipt { max-width: 720px; margin: 0 auto; background: #ffffff; border: 1px solid #e2e8f0; border-radius: 24px; overflow: hidden; }
      .hero { padding: 24px; background: linear-gradient(135deg, #0f766e, #059669); color: white; }
      .hero h1 { margin: 0 0 8px; font-size: 28px; }
      .hero p { margin: 0; opacity: 0.9; }
      .content { padding: 24px; }
      .amount { font-size: 32px; font-weight: 800; color: #0f766e; margin: 0 0 16px; }
      .grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 12px; margin-top: 20px; }
      .item { background: #f8fafc; border-radius: 16px; padding: 16px; }
      .item span { display: block; font-size: 12px; text-transform: uppercase; letter-spacing: 0.08em; color: #64748b; margin-bottom: 8px; }
      .footer { padding: 20px 24px 24px; color: #475569; font-size: 13px; }
      @media print { body { background: white; padding: 0; } .receipt { border: 0; border-radius: 0; } }
    </style>
  </head>
  <body>
    <section class="receipt">
      <div class="hero">
        <h1>Connect Receipt</h1>
        <p>${receiptNumber}</p>
      </div>
      <div class="content">
        <p class="amount">${amount}</p>
        <p><strong>Account Holder:</strong> ${profile.displayName}</p>
        <p><strong>Transaction:</strong> ${meta.title}</p>
        ${counterpartyLine}
        <p><strong>Status:</strong> ${tx.status}</p>
        <p><strong>Method:</strong> ${tx.method}</p>
        <p><strong>Date:</strong> ${createdAt}</p>
        <div class="grid">
          <div class="item">
            <span>Wallet Currency</span>
            <strong>${tx.currency}</strong>
          </div>
          <div class="item">
            <span>Transaction ID</span>
            <strong>${tx.id}</strong>
          </div>
          <div class="item">
            <span>User ID</span>
            <strong>${profile.publicId || profile.uid}</strong>
          </div>
          <div class="item">
            <span>Reference</span>
            <strong>${tx.reference || 'N/A'}</strong>
          </div>
        </div>
      </div>
      <div class="footer">
        This receipt was generated by Connect and can be saved or shared for your records.
      </div>
    </section>
  </body>
</html>`;
}

export default function Wallets({ profile }: WalletsProps) {
  const navigate = useNavigate();
  const { currency, setCurrency } = useCurrency();

  const [wallet, setWallet] = useState<Wallet | null>(null);
  const [transactions, setTransactions] = useState<WalletTransaction[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null);

  const [activeAction, setActiveAction] = useState<WalletAction>(null);
  const [amount, setAmount] = useState(0);
  const [method, setMethod] = useState<'card' | 'transfer'>('card');
  const [submitting, setSubmitting] = useState(false);

  const loadWalletData = async () => {
    setLoading(true);
    setError(null);
    try {
      const [walletData, tx] = await Promise.all([
        supabaseService.getOrCreateWallet(profile.uid),
        supabaseService.listWalletTransactions(profile.uid),
      ]);
      setWallet(walletData);
      setTransactions(tx);
    } catch (e: any) {
      setError(e.message || 'Failed to load wallet.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    setLoading(true);
    setError(null);

    const unsubscribeWallet = supabaseService.subscribeToWallet(
      profile.uid,
      (walletData) => {
        setWallet(walletData);
        setLoading(false);
      },
      (nextError) => {
        setError(nextError?.message || 'Failed to load wallet.');
        setLoading(false);
      }
    );

    const unsubscribeTransactions = supabaseService.subscribeToWalletTransactions(
      profile.uid,
      (tx) => {
        setTransactions(tx);
        setLoading(false);
      },
      (nextError) => {
        setError(nextError?.message || 'Failed to load wallet transactions.');
        setLoading(false);
      }
    );

    return () => {
      unsubscribeWallet();
      unsubscribeTransactions();
    };
  }, [profile.uid]);

  const availableBalance = useMemo(() => {
    if (!wallet) return 0;
    if (currency === 'USD') return wallet.usdBalance;
    if (currency === 'NGN') return wallet.ngnBalance;
    return wallet.eurBalance;
  }, [wallet, currency]);

  const balances = useMemo(
    () => [
      { code: 'USD' as WalletCurrency, value: wallet?.usdBalance || 0 },
      { code: 'NGN' as WalletCurrency, value: wallet?.ngnBalance || 0 },
      { code: 'EUR' as WalletCurrency, value: wallet?.eurBalance || 0 },
    ],
    [wallet]
  );

  const submitAction = async (e: React.FormEvent) => {
    e.preventDefault();
    setError(null);
    setSuccess(null);

    if (!activeAction) return;
    if (amount <= 0 || Number.isNaN(amount)) {
      setError('Enter a valid amount.');
      return;
    }

    setSubmitting(true);
    try {
      if (activeAction === 'add') {
        await supabaseService.topUpWallet(profile.uid, currency, amount, method);
        setSuccess('Funds added successfully.');
      } else {
        await supabaseService.withdrawFromWallet(profile.uid, currency, amount, method);
        setSuccess('Withdrawal successful.');
      }

      setAmount(0);
      setActiveAction(null);
      await loadWalletData();
    } catch (e: any) {
      setError(e.message || 'Transaction failed.');
    } finally {
      setSubmitting(false);
    }
  };

  const downloadReceipt = (tx: WalletTransaction) => {
    const markup = buildReceiptMarkup(profile, tx);
    const blob = new Blob([markup], { type: 'text/html;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement('a');
    anchor.href = url;
    anchor.download = `connect-receipt-${tx.id.slice(0, 8)}.html`;
    document.body.appendChild(anchor);
    anchor.click();
    anchor.remove();
    URL.revokeObjectURL(url);
  };

  const shareReceipt = async (tx: WalletTransaction) => {
    const markup = buildReceiptMarkup(profile, tx);
    const file = new File([markup], `connect-receipt-${tx.id.slice(0, 8)}.html`, { type: 'text/html' });
    const meta = getTransactionMeta(tx);
    const text = `${meta.title}\n${formatAmount(tx.amount, tx.currency)}\n${format(new Date(tx.createdAt), 'PPP p')}\nReceipt ID: ${tx.id}`;

    try {
      if (navigator.share && navigator.canShare?.({ files: [file] })) {
        await navigator.share({
          title: 'Connect Receipt',
          text,
          files: [file],
        });
        return;
      }

      if (navigator.share) {
        await navigator.share({
          title: 'Connect Receipt',
          text,
        });
        return;
      }

      downloadReceipt(tx);
    } catch {
      downloadReceipt(tx);
    }
  };

  if (loading) {
    return (
      <div className="mx-auto max-w-5xl px-4 py-8">
        <div className="h-8 w-8 animate-spin rounded-full border-b-2 border-teal-600"></div>
      </div>
    );
  }

  return (
    <div className="mx-auto max-w-5xl space-y-6 px-4 py-8">
      <div className="flex items-center gap-3">
        <button onClick={() => navigate(-1)} className="rounded-full p-2 hover:bg-gray-100">
          <ArrowLeft size={20} className="text-gray-600" />
        </button>
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Wallet</h1>
          <p className="text-sm text-gray-500">Manage balances, transfers, withdrawals and history.</p>
        </div>
        <button
          onClick={loadWalletData}
          className="ml-auto flex items-center gap-2 rounded-xl border border-gray-200 bg-white px-3 py-2 text-sm font-semibold hover:bg-gray-50"
        >
          <RefreshCw size={16} />
          Refresh
        </button>
      </div>

      <div className="space-y-5 rounded-3xl bg-gradient-to-br from-teal-700 to-emerald-700 p-5 text-white shadow-lg md:p-7">
        <div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between">
          <div>
            <p className="text-xs uppercase tracking-wider opacity-80">Available Balance</p>
            <p className="mt-1 text-2xl font-black md:text-3xl">{formatAmount(availableBalance, currency)}</p>
            <button
              type="button"
              onClick={() => navigate('/settings?section=security')}
              className="mt-2 text-xs font-semibold text-white/85 underline underline-offset-4 hover:text-white"
            >
              Manage transfer PIN in Security
            </button>
          </div>
          <div className="grid w-full gap-2 sm:grid-cols-3 md:w-auto">
            {balances.map((item) => (
              <button
                key={item.code}
                type="button"
                onClick={() => setCurrency(item.code)}
                className={`rounded-2xl border px-3 py-3 text-left transition-all ${
                  currency === item.code ? 'border-white bg-white text-teal-700 shadow-sm' : 'border-white/25 bg-white/10 hover:bg-white/15'
                }`}
              >
                <p className={`text-[11px] font-bold uppercase tracking-wider ${currency === item.code ? 'text-teal-700/80' : 'text-white/70'}`}>
                  {item.code}
                </p>
                <p className="mt-1 text-sm font-bold">{formatAmount(item.value, item.code)}</p>
              </button>
            ))}
          </div>
        </div>

        <div className="grid grid-cols-1 gap-2 sm:grid-cols-3 md:gap-3">
          <button
            onClick={() => navigate('/wallets/transfer')}
            className="inline-flex items-center justify-center gap-2 rounded-xl border border-white bg-white py-2.5 text-sm font-bold text-teal-700"
          >
            <SendHorizontal size={16} />
            Transfer
          </button>
          <button
            onClick={() => setActiveAction((prev) => (prev === 'withdraw' ? null : 'withdraw'))}
            className={`inline-flex items-center justify-center gap-2 rounded-xl border py-2.5 text-sm font-bold ${
              activeAction === 'withdraw' ? 'border-white bg-white text-teal-700' : 'border-white/30 bg-white/15 hover:bg-white/20'
            }`}
          >
            <ArrowUpRight size={16} />
            Withdraw
          </button>
          <button
            onClick={() => setActiveAction((prev) => (prev === 'add' ? null : 'add'))}
            className={`inline-flex items-center justify-center gap-2 rounded-xl border py-2.5 text-sm font-bold ${
              activeAction === 'add' ? 'border-white bg-white text-teal-700' : 'border-white/30 bg-white/15 hover:bg-white/20'
            }`}
          >
            <PlusCircle size={16} />
            Add Funds
          </button>
        </div>

        {activeAction && (
          <form onSubmit={submitAction} className="space-y-3 rounded-2xl border border-white/25 bg-white/10 p-4">
            <div className="space-y-1">
              <label className="text-xs font-semibold opacity-90">Amount ({currency})</label>
              <input
                type="number"
                min="0"
                step="0.01"
                value={amount || ''}
                onChange={(e) => setAmount(parseFloat(e.target.value))}
                className="w-full rounded-xl bg-white px-3 py-2.5 text-sm text-gray-900 outline-none"
                required
              />
            </div>

            <div className="flex gap-2">
              {(['card', 'transfer'] as const).map((item) => (
                <button
                  key={item}
                  type="button"
                  onClick={() => setMethod(item)}
                  className={`inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-xs font-semibold ${
                    method === item ? 'border-white bg-white text-teal-700' : 'border-white/30 bg-white/15'
                  }`}
                >
                  {item === 'card' ? <PlusCircle size={14} /> : <Landmark size={14} />}
                  {item === 'card' ? 'Card' : 'Transfer'}
                </button>
              ))}
            </div>

            <button
              type="submit"
              disabled={submitting}
              className="w-full rounded-xl bg-white py-2.5 text-sm font-bold text-teal-700 hover:bg-gray-100 disabled:opacity-70"
            >
              {submitting ? 'Processing...' : activeAction === 'add' ? 'Add Funds' : 'Withdraw'}
            </button>
          </form>
        )}
      </div>

      {error && <div className="rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</div>}
      {success && <div className="rounded-xl bg-emerald-50 p-3 text-sm font-semibold text-emerald-700">{success}</div>}

      <div className="rounded-3xl border border-gray-200 bg-white p-5">
        <h2 className="mb-4 text-lg font-bold text-gray-900">Transaction Histories</h2>
        {transactions.length === 0 ? (
          <p className="text-sm text-gray-500">No transactions yet.</p>
        ) : (
          <div className="space-y-3">
            {transactions.map((tx) => {
              const isCredit = tx.type === 'topup';
              const isTransferOut = tx.reference?.startsWith('transfer_out:');
              const isTransferIn = tx.reference?.startsWith('transfer_in:');
              const meta = getTransactionMeta(tx);

              return (
                <div key={tx.id} className="rounded-2xl border border-gray-100 p-3">
                  <div className="flex items-center justify-between gap-3">
                    <div className="flex min-w-0 items-center gap-3">
                      <div
                        className={`flex h-10 w-10 items-center justify-center rounded-xl ${
                          isCredit ? 'bg-emerald-50 text-emerald-600' : 'bg-amber-50 text-amber-600'
                        }`}
                      >
                        {isTransferIn ? <SendHorizontal size={17} className="rotate-180" /> : isTransferOut ? <SendHorizontal size={17} /> : isCredit ? <ArrowDownLeft size={17} /> : <ArrowUpRight size={17} />}
                      </div>
                      <div className="min-w-0">
                        <p className="text-sm font-bold text-gray-900">{meta.title}</p>
                        <p className="truncate text-xs text-gray-500">
                          {meta.counterparty ? `User ID: ${meta.counterparty} · ` : ''}
                          {format(new Date(tx.createdAt), 'MMM d, yyyy, h:mm a')}
                        </p>
                      </div>
                    </div>
                    <div className="text-right">
                      <p className="text-sm font-bold text-gray-900">{formatAmount(tx.amount, tx.currency)}</p>
                      <p className="text-[10px] font-bold uppercase tracking-wider text-gray-400">{tx.status}</p>
                    </div>
                  </div>

                  <div className="mt-3 flex flex-wrap gap-2">
                    <button
                      type="button"
                      onClick={() => downloadReceipt(tx)}
                      className="inline-flex items-center gap-1.5 rounded-xl bg-gray-100 px-3 py-2 text-xs font-semibold text-gray-700 hover:bg-gray-200"
                    >
                      <Download size={14} />
                      Download Receipt
                    </button>
                    <button
                      type="button"
                      onClick={() => void shareReceipt(tx)}
                      className="inline-flex items-center gap-1.5 rounded-xl bg-teal-50 px-3 py-2 text-xs font-semibold text-teal-700 hover:bg-teal-100"
                    >
                      <Share2 size={14} />
                      Share Receipt
                    </button>
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </div>
    </div>
  );
}
